<div class="container mt-5">
    <div class="row">    
        Adatainak védelme fontos számunkra! Ebben a tájékoztatóban minden információt megtalál az adatai kezelésével kapcsolatban. 
        Kérjük, olvassa el figyelmesen. Amennyiben kifogásolja az adatvédelmi eljárásunkat, vagy nem ért egyet a módszerrel, bátran
        keressen fel minket a weboldalon feltüntetett elérhetőségek valamelyikén!
    </div>
    <div class="row"> 
        <h2 style = "color: royalblue; padding:10px;">Személyes adatok begyűjtése</h2>
        <p>Lorem ipsum dolor sit amet consectetuer dolor interdum et nunc id. Id condimentum et ac vel enim hac dapibus tempus Phasellus et. Aliquet parturient augue Aenean sagittis malesuada purus eget tortor purus tincidunt. Ultrices Maecenas sollicitudin pellentesque Praesent quis pellentesque Vestibulum lacinia Phasellus et. Laoreet dictum Pellentesque nunc aliquam commodo malesuada facilisis a quis mauris. Felis vel facilisis id rutrum est sapien congue Vestibulum commodo.</p>
        <p>Aenean nunc Curabitur Phasellus ante auctor commodo id et tincidunt eu. Id cursus Ut facilisi nibh eu fames quam pede morbi non. Lacus quis ultrices accumsan pede Nullam amet justo tortor eros fringilla. Aenean id nec hendrerit et Aenean molestie malesuada magna ligula dui. Risus dui molestie interdum nunc amet elit quis rhoncus pede Aliquam. Semper Mauris Nulla et ultrices orci sed nulla Integer augue tellus. Egestas Integer.</p>
        <p>A turpis tincidunt id Integer suscipit sit Maecenas sodales metus diam. Mauris dignissim enim faucibus neque metus quis lacinia Quisque vitae eget. Et Cras elit et elit quis Cras lacus pretium sapien sed. Pellentesque adipiscing magnis tincidunt ante dui Morbi Praesent diam consectetuer lorem. Suspendisse velit natoque eu congue sodales libero Nullam wisi ut elit. Amet et Donec nunc laoreet pretium Phasellus Duis malesuada Aenean dui. Aenean tempus.</p>
        <p>Nonummy volutpat venenatis non quis mi vitae sem Curabitur risus Aenean. Vestibulum quis Sed dolor turpis elit nibh non nulla tincidunt vitae. Consectetuer facilisi lacinia condimentum elit Donec orci neque ligula Vestibulum mauris. Aliquet ac ac tempor mollis metus vitae a tellus metus dui. Convallis Nam Nulla neque malesuada pede elit iaculis quis congue habitant. Tortor sollicitudin et dictum Morbi Curabitur vel lacinia Vestibulum Ut.</p>

        <h2 style = "color: royalblue; padding:10px;">Személyes adatok felhasználása</h2>
        <p>Lorem ipsum dolor sit amet consectetuer dolor interdum et nunc id. Id condimentum et ac vel enim hac dapibus tempus Phasellus et. Aliquet parturient augue Aenean sagittis malesuada purus eget tortor purus tincidunt. Ultrices Maecenas sollicitudin pellentesque Praesent quis pellentesque Vestibulum lacinia Phasellus et. Laoreet dictum Pellentesque nunc aliquam commodo malesuada facilisis a quis mauris. Felis vel facilisis id rutrum est sapien congue Vestibulum commodo.</p>
        <p>Aenean nunc Curabitur Phasellus ante auctor commodo id et tincidunt eu. Id cursus Ut facilisi nibh eu fames quam pede morbi non. Lacus quis ultrices accumsan pede Nullam amet justo tortor eros fringilla. Aenean id nec hendrerit et Aenean molestie malesuada magna ligula dui. Risus dui molestie interdum nunc amet elit quis rhoncus pede Aliquam. Semper Mauris Nulla et ultrices orci sed nulla Integer augue tellus. Egestas Integer.</p>
        <p>A turpis tincidunt id Integer suscipit sit Maecenas sodales metus diam. Mauris dignissim enim faucibus neque metus quis lacinia Quisque vitae eget. Et Cras elit et elit quis Cras lacus pretium sapien sed. Pellentesque adipiscing magnis tincidunt ante dui Morbi Praesent diam consectetuer lorem. Suspendisse velit natoque eu congue sodales libero Nullam wisi ut elit. Amet et Donec nunc laoreet pretium Phasellus Duis malesuada Aenean dui. Aenean tempus.</p>
        <p>Nonummy volutpat venenatis non quis mi vitae sem Curabitur risus Aenean. Vestibulum quis Sed dolor turpis elit nibh non nulla tincidunt vitae. Consectetuer facilisi lacinia condimentum elit Donec orci neque ligula Vestibulum mauris. Aliquet ac ac tempor mollis metus vitae a tellus metus dui. Convallis Nam Nulla neque malesuada pede elit iaculis quis congue habitant. Tortor sollicitudin et dictum Morbi Curabitur vel lacinia Vestibulum Ut.</p>
    </div>
</div>